Trucks/force-app/main/default/objects/Truck__c/Truck__c.object-meta.xml
<CustomObject>
    <description>This is a custom field that will be used to track all the cars in this field</description>
    <label>Truck</label>
    <nameField>
        <label>Trucks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trucks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trucks/force-app/main/default/objects/Truck__c/fields/Insurance_Number__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Number__c</fullName>
    <description>This is the insurance number of the vehicle.</description>
    <label>Insurance Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Trucks/force-app/main/default/objects/Truck__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>This display the location that determine the latitude and longitude of the vehicles.</description>
    <label>Location</label>
    <scale>6</scale>
    <type>Location</type>
</CustomField>

Trucks/force-app/main/default/objects/Truck__c/fields/Number_Plate__c.field-meta.xml
<CustomField>
    <fullName>Number_Plate__c</fullName>
    <description>This is the car number of the vehicle</description>
    <inlineHelpText>Car number should have both Alphabets and Numbers</inlineHelpText>
    <label>Number Plate</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Trucks/force-app/main/default/objects/Truck__c/fields/Observations__c.field-meta.xml
<CustomField>
    <fullName>Observations__c</fullName>
    <label>Observations</label>
    <type>TextArea</type>
</CustomField>

Trucks/force-app/main/default/objects/Truck__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <description>This is the date the vehicle was registered</description>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

Trucks/force-app/main/default/classes/TruckController.cls
public with sharing class TruckController {
    @AuraEnabled(cacheable=true scope='global')
    public static Truck__c[] getAllTrucks() {
       return [
    SELECT
        Id,
        Name,
        Insurance_Number__c,
        Observations__c,
        Registration_Date__c,
        Location__c,
        Number_Plate__c
    FROM Truck__c
    WITH SECURITY_ENFORCED  
    ORDER BY Name
    LIMIT 50  
       ];

    }

    @AuraEnabled(cacheable=true scope='global')
    public static Truck__c[] searchTrucks(String searchTerm) {
        // Return all bears when no search term
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllTrucks();
        }
        // Prepare query parameters
        searchTerm = '%' + searchTerm + '%';
        // Execute search query
        return [
            SELECT
               Id,
               Name,
               Insurance_Number__c,
               Observations__c,
               Registration_Date__c,
               Location__c,
               Number_Plate__c
           FROM Truck__c
           WITH SECURITY_ENFORCED  
           ORDER BY Name
           LIMIT 50  
              ];
    }
}